"""create_admin_user

Revision ID: 4c79ec5a98c1
Revises: fb0c9a021c5d
Create Date: 2020-02-20 22:50:39.559221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c79ec5a98c1'
down_revision = 'fb0c9a021c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
