"""create_super_admin_user

Revision ID: 81d3c1733087
Revises: 4c79ec5a98c1
Create Date: 2020-02-20 22:50:40.534201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d3c1733087'
down_revision = '4c79ec5a98c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
